### ISSUE TITLE
jaxlib version

### ISSUE THREAD

**Issue by joglekara** [f0uriest/interpax#11]
Great work that fills a clear need IMO!!

Any thoughts on bumping jax/jaxlib to 0.4.20?

**Comment by joglekara** [comment]
perhaps we can do a `>=` like in https://github.com/patrick-kidger/equinox/blob/main/pyproject.toml

Happy to send in a tested PR

**Comment by f0uriest** [comment]
I'm fine with bumping it, but I prefer to keep a cap (`<=`) on the max version since JAX is still in `v0.x.y` so no guaranteed API consistency.

**Comment by allen-adastra** [comment]
https://github.com/f0uriest/interpax/pull/12 fixed this.
